language: python
sudo: required
install:
- pip install flask
- pip install -r requirements.txt
script: nosetests app.py
deploy:
  provider: heroku
  api_key:
    secure: Usw1bIavkaMCchoFOmLC97vz4KmtMxpdNpumiZh3GTskdkznu+cDjfoLe3zfHlrZkQji4aBjtt3ZiG468cbrzBUn+fAyLu+ziC6H1d4pzHAmFaa+zJ9rY5JJ5Qd6Zk7of2uASCvcgRhykX/e0eFTZAYCERDUMKIDLYXq1EykLjbRNJ2NfUPcmaDpJn1UwyqN2y/irYrBPpA5Xurqu0GQDLQQzByZWon5NIGLNnh82iiFC3M3YfNcMhQJCA752L0J/tg+0RwZnbHvBn+jmKMZuhiXn7udvE8g4sUmwsu/4LBmHqLx/ehXsWniiQUSKIqlngB/bWJw85RXG8nzEpDIBjCfsul8lMDZxfWaxYr+02YZM4UpIu3qSHjH70JFAu8PiLr2pnsVafkrY3Lac0Xj+kwL/y8aETUuMW54m7SUbYvSv0kYCf2TfS/QdNkv2YBl5eTmq9uOxJLok9Nk4hXXFRuFORC64QTsEAkgqhbR8YVTjKGvJrl27mFPpJHPVrKiOZ1EUzho+KujhQYZr3czDv4QXkJmzGs3MExX//2HoyvXL7pj4w2dbgpiNwqEFj2io8b9WHgfHyVHzomfUHhsdiI04JZEDMjLudFD01r+/FII5YmWpWBlGeY8B2Rjd68uRDfd7DvSaRgGNg5VbbCr5gZu5DPhTqkjyX03fVrXLLw=
  app: meilix-generator
  on:
    repo: meets2tarun/meilix-generator
