language: python
python:
- 3.6
sudo: required
install: pip install -r requirements.txt
script: # nosetests app.py
deploy:
  provider: heroku
  api_key:
    secure: nt5cAubuYPgzP9j+efg8r6i0U8t3qnZ7DlR1hJ//i5kCMJl41aYqB4zkPFGkHpm7EAVYkZTzlplB+gkSF3goZL+h7aJ/XLwFlRtVyKtTsMPsI0UWc7gvJlDrGEdTDlOUokyotEXVY/CcsXCFBPT9Sx2elpueF6o8UqOVmQ5lmlaf0E85fvLPtvrpu3dird0dI65lcdsPTiT+49mduCPrzf+ILKkvLb6i2CuOKPbroGLorjIHAgvy7Axuhnc1ahSWpS58UhLS4VgtfFQMHxKVrOgUpp/ATDASExnG63VmL1MMlnMWYnwbX8FhVE+/7CvZfkPsbHii5xClrUjG7aGJovgURcpP07ILEz+ppkC0E5jDgFXKZ2IKVC5XoE2PTB0CtuQ6qIKZ5gvVbvuGe4PfIidtenfbewjES9V7mSqYarLFIIdcEJ8fLWnZx4PQxPYzOx+sTIwrrLYM1VSqlWHGLcnmDKaMbL7Zc5Pv/JrDi0xTIaQLOc2qPhcEfzh+LhNumjuh9eQMX5PzcZ72Hg9yVFT0hfgmTXWiRLrU1wi8Es+/PYBfOxlGligGlTceMc+HoQqgA1gAx5QS/fFlAgLDAbin3StZfv8ZzsrRaLucUeRc1j5VEb+m/Z3a7u6pQH2c5xmMRyUiDtF3Xfg+32fXr+dCv968tSVKWV6zjn8no9w=
  app: meilix-generator
  on:
    repo: fossasia/meilix-generator
